In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
#Defining the folder path

data = '../Data'
model_path = '../Model'
notbook_path = '../Notebook'
Transformation_path = '../Transformation'


In [3]:
import os
os.getcwd()
os.chdir(data)

In [4]:
#Loading the dataset with function
admission_data = pd.read_csv('admission_data.csv')
admission_data.head()


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [5]:
admission_data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [6]:
admission_data['Serial No.']

0        1
1        2
2        3
3        4
4        5
      ... 
395    396
396    397
397    398
398    399
399    400
Name: Serial No., Length: 400, dtype: int64

In [7]:
#removing the Serial No.
admission_data.drop(columns ='Serial No.', axis=1,inplace=True)
admission_data

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
395        324          110                  3  3.5   3.5  9.04         1   
396        325          107                  3  3.0   3.5  9.11         1   
397        330          116                  4  5.0   4.5  9.45         1   
398        312          103                  3  3.5   4.0  8.78         0   
399        333          117                  4  5.0   4.0  9.66         1   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
395              0.82  
396              0.84  
397              0.91  
398              0.67  
399              0.95  

[400 rows x 8 columns]

In [8]:
#Data preprocessing
admission_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GRE Score          400 non-null    int64  
 1   TOEFL Score        400 non-null    int64  
 2   University Rating  400 non-null    int64  
 3   SOP                400 non-null    float64
 4   LOR                400 non-null    float64
 5   CGPA               400 non-null    float64
 6   Research           400 non-null    int64  
 7   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 25.1 KB


In [9]:
admission_data.shape

(400, 8)

In [10]:
admission_data.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR   \
count  400.000000   400.000000         400.000000  400.000000  400.000000   
mean   316.807500   107.410000           3.087500    3.400000    3.452500   
std     11.473646     6.069514           1.143728    1.006869    0.898478   
min    290.000000    92.000000           1.000000    1.000000    1.000000   
25%    308.000000   103.000000           2.000000    2.500000    3.000000   
50%    317.000000   107.000000           3.000000    3.500000    3.500000   
75%    325.000000   112.000000           4.000000    4.000000    4.000000   
max    340.000000   120.000000           5.000000    5.000000    5.000000   

             CGPA    Research  Chance of Admit   
count  400.000000  400.000000        400.000000  
mean     8.598925    0.547500          0.724350  
std      0.596317    0.498362          0.142609  
min      6.800000    0.000000          0.340000  
25%      8.170000    0.000000          0.640000  
50%      8.610000    1.000000          0.730000  
75%      9.062500    1.000000          0.830000  
max      9.920000    1.000000          0.970000

In [11]:
admission_data.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

Selecting Numerical Columns

In [12]:
admission_data.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [13]:
admission_data.columns=['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance_of_Admit']

In [14]:
Num_cols=['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP',
       'LOR ', 'CGPA', 'Research']

In [15]:
num_data=admission_data[Num_cols]

In [16]:
num_data

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [17]:
Target=admission_data['Chance_of_Admit']
Target

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance_of_Admit, Length: 400, dtype: float64

Standardizing the Numerical columns

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()
scaler


StandardScaler()

In [20]:
scaler.fit(num_data)

StandardScaler()

In [21]:
num_data = scaler.transform(num_data)
num_data

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [22]:
round(num_data.mean()), round(num_data.std())

(0, 1)

Convert the Numerical data transformed to dataframe

In [23]:
target_data = Target.reset_index(drop=True)
target_data

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance_of_Admit, Length: 400, dtype: float64

In [24]:
num_data_df = pd.DataFrame(num_data, columns=Num_cols)
num_data_df.head()

GRE_Score  TOEFL_Score  University_Rating       SOP      LOR       CGPA  \
0   1.762107     1.746971           0.798829  1.093864  1.167321  1.764818   
1   0.627656    -0.067635           0.798829  0.596653  1.167321  0.455151   
2  -0.070467    -0.562528          -0.076600 -0.397769  0.052933 -1.005631   
3   0.453126     0.427257          -0.076600  0.099442 -1.061454  0.119339   
4  -0.244998    -0.727492          -0.952029 -1.392191 -0.504260 -0.653029   

   Research  
0  0.909112  
1  0.909112  
2  0.909112  
3  0.909112  
4 -1.099975

Concatenate the num_data_df and target

In [25]:
cleaned_data= pd.concat([num_data_df, Target], axis=1)
cleaned_data.head()

GRE_Score  TOEFL_Score  University_Rating       SOP      LOR       CGPA  \
0   1.762107     1.746971           0.798829  1.093864  1.167321  1.764818   
1   0.627656    -0.067635           0.798829  0.596653  1.167321  0.455151   
2  -0.070467    -0.562528          -0.076600 -0.397769  0.052933 -1.005631   
3   0.453126     0.427257          -0.076600  0.099442 -1.061454  0.119339   
4  -0.244998    -0.727492          -0.952029 -1.392191 -0.504260 -0.653029   

   Research  Chance_of_Admit  
0  0.909112             0.92  
1  0.909112             0.76  
2  0.909112             0.72  
3  0.909112             0.80  
4 -1.099975             0.65

In [26]:
cleaned_data.isna().sum()

GRE_Score            0
TOEFL_Score          0
University_Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance_of_Admit      0
dtype: int64

Select Features X and Target y

# converting to array

In [27]:
cleaned_df_arr = cleaned_data.values

cleaned_df_arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.76481828,
         0.90911166,  0.92      ],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  0.45515126,
         0.90911166,  0.76      ],
       [-0.07046681, -0.56252785, -0.07660001, ..., -1.00563118,
         0.90911166,  0.72      ],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.42900622,
         0.90911166,  0.91      ],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.30403584,
        -1.09997489,  0.67      ],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  1.78160888,
         0.90911166,  0.95      ]])

In [28]:
X = cleaned_df_arr[:, :-1]
y = cleaned_df_arr[:, -1]

In [29]:
#Train_Test_Split
from sklearn.model_selection import train_test_split


In [30]:
seed = 42

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=seed)

In [31]:
X_train=pd.DataFrame(X_train, columns=Num_cols)
X_train

GRE_Score  TOEFL_Score  University_Rating       SOP      LOR       CGPA  \
0    -1.379448    -1.717277          -0.952029 -0.397769 -0.504260 -1.207118   
1     2.023903     1.252078           1.674257  1.093864  1.167321  1.429006   
2    -1.728509    -1.882241          -0.952029 -0.894980 -2.175842 -1.190328   
3    -1.204917    -1.387349          -0.076600 -1.392191 -1.061454 -1.576512   
4    -0.419528    -0.397564          -0.952029 -1.392191 -1.061454 -0.250054   
..         ...          ...                ...       ...       ...       ...   
391   1.674841     0.757186           1.674257  1.591075  1.724515  1.949515   
392   1.063983     0.592221           0.798829  1.093864  1.167321  0.975660   
393  -0.943121    -0.397564          -0.952029 -0.894980 -0.504260 -0.636238   
394  -1.292182    -1.387349          -1.827457 -1.392191 -1.618648 -2.264926   
395  -0.244998    -0.232599          -0.952029  0.596653  0.052933 -0.585866   

     Research  
0    0.909112  
1    0.909112  
2   -1.099975  
3   -1.099975  
4   -1.099975  
..        ...  
391  0.909112  
392  0.909112  
393  0.909112  
394 -1.099975  
395 -1.099975  

[396 rows x 7 columns]

In [32]:
X_test=pd.DataFrame(X_test, columns=Num_cols)
X_test

GRE_Score  TOEFL_Score  University_Rating       SOP      LOR       CGPA  \
0  -1.379448    -0.562528          -0.076600  0.099442  0.610127 -0.804144   
1  -0.506794    -0.892456          -0.076600  1.093864  0.610127  0.068967   
2   2.023903     1.087114           1.674257  0.596653  0.610127  1.680865   
3   0.714922     0.097329           0.798829  1.093864  0.610127  0.774173   

   Research  
0  0.909112  
1  0.909112  
2  0.909112  
3  0.909112

In [33]:
y_train=pd.DataFrame(y_train)
y_train

0
0    0.44
1    0.94
2    0.43
3    0.36
4    0.72
..    ...
391  0.96
392  0.87
393  0.72
394  0.57
395  0.62

[396 rows x 1 columns]

In [34]:
y_test=pd.DataFrame(y_test)
y_test

0
0  0.68
1  0.68
2  0.90
3  0.79

In [35]:
#Train the model
from sklearn.linear_model import LinearRegression

In [36]:
log_reg = LinearRegression()
log_reg

LinearRegression()

In [37]:
log_reg.fit(X_train, y_train)

LinearRegression()

In [38]:
#predicting with the model

y_pred = log_reg.predict(X_test)
y_pred[:10]

array([[0.65191231],
       [0.72349591],
       [0.93651038],
       [0.82117846]])

In [39]:
y_test[:10]

0
0  0.68
1  0.68
2  0.90
3  0.79

In [40]:
y_pred[:10] == y_test[:10]

0
0  False
1  False
2  False
3  False

In [41]:
score=log_reg.score(X_test,y_test)

In [42]:
score

0.8501602905834911

In [43]:
#Evaluating the model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [44]:
y_pred

array([[0.65191231],
       [0.72349591],
       [0.93651038],
       [0.82117846]])

In [45]:
mse = mean_squared_error(y_test, y_pred)
mse

0.0012464790827085832

In [46]:
rmse = np.sqrt(mse)
rmse

0.035305510656391634

In [47]:
mae = mean_absolute_error(y_test, y_pred)
mae

0.034818108923968444

In [48]:
r2 = r2_score(y_test, y_pred)
r2

0.8501602905834911

In [49]:
def model_training(data, target_col, model, test_size, seed):
    
    X = data.drop(columns=[target_col])
    y = data[target_col]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
    

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    #score = model.score(X_test, y_test)

    return X_train, X_test, y_train, y_test, y_pred

In [50]:
from sklearn.tree import DecisionTreeRegressor

In [51]:
DecisionModel=DecisionTreeRegressor()

In [52]:
DecisionModel.fit(X_train, y_train)

DecisionTreeRegressor()

In [53]:
#predicting with the model

y_pred = DecisionModel.predict(X_test)
y_pred[:10]

array([0.66, 0.76, 0.92, 0.8 ])

In [54]:
y_test

0
0  0.68
1  0.68
2  0.90
3  0.79

In [55]:
y_pred

array([0.66, 0.76, 0.92, 0.8 ])

In [56]:
score=log_reg.score(X_test,y_test)
score

0.8501602905834911

In [57]:
mse = mean_squared_error(y_test, y_pred)
mse

0.0018250000000000035

In [58]:
mae = mean_absolute_error(y_test, y_pred)
mae

0.03250000000000003

In [59]:
r2 = r2_score(y_test, y_pred)
r2

0.7806160781367388

In [60]:
model_name='Linear Regression'
print(f'Below is the Evaluation for {model_name} model')
print('--------------------------------------------------')
print(f'The mean_squared_error is {round(mse,2)}')
print('--------------------------------------------------')
print(f'The root_mean_squared_error is {round(rmse,2)}')
print('--------------------------------------------------')
print(f'The mean_absolute_error is {round(mae,2)}')
print('--------------------------------------------------')
print(f'The cofficient_of_determination(r2) is {round(r2,2)*100}% ')

Below is the Evaluation for Linear Regression model
--------------------------------------------------
The mean_squared_error is 0.0
--------------------------------------------------
The root_mean_squared_error is 0.04
--------------------------------------------------
The mean_absolute_error is 0.03
--------------------------------------------------
The cofficient_of_determination(r2) is 78.0% 


In [61]:
from sklearn.linear_model import LinearRegression,ElasticNet, Ridge

In [62]:
#using elastic regressor


In [63]:
ElasticModel=ElasticNet()

In [64]:
ElasticModel.fit(X_train, y_train)

ElasticNet()

In [65]:
#predicting with the model

y_pred = ElasticModel.predict(X_test)
y_pred

array([0.72396465, 0.72396465, 0.72396465, 0.72396465])

In [66]:
rmse = np.sqrt(mse)
rmse

0.0427200187265877

In [67]:
mae = mean_absolute_error(y_test, y_pred)
mae

0.08249999999999999

In [68]:
r2 = r2_score(y_test, y_pred)
r2

-0.17850920776494927

In [69]:
model_name='Elastic Net'
print(f'Below is the Evaluation for {model_name} model')
print('--------------------------------------------------')
print(f'The mean_squared_error is {round(mse,2)}')
print('--------------------------------------------------')
print(f'The root_mean_squared_error is {round(rmse,2)}')
print('--------------------------------------------------')
print(f'The mean_absolute_error is {round(mae,2)}')
print('--------------------------------------------------')
print(f'The cofficient_of_determination(r2) is {round(r2,2)*100}% ')

Below is the Evaluation for Elastic Net model
--------------------------------------------------
The mean_squared_error is 0.0
--------------------------------------------------
The root_mean_squared_error is 0.04
--------------------------------------------------
The mean_absolute_error is 0.08
--------------------------------------------------
The cofficient_of_determination(r2) is -18.0% 


In [70]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor,StackingRegressor,GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

In [71]:
data =cleaned_data
target_col = 'Chance_of_Admit' 
test_size = 0.020 
seed = 40
model=AdaBoostRegressor()
X_train, X_test, y_train, y_test,y_pred = model_training(data, target_col, model, test_size, seed)
y_pred_ada = y_pred 

In [72]:
y_pred_ada[:10]

array([0.63976744, 0.58863469, 0.74385714, 0.74738095, 0.76492958,
       0.64152542, 0.81096774, 0.68794118])

In [73]:
AdaB= AdaBoostRegressor()
AdaB

AdaBoostRegressor()

In [74]:
AdaB.fit(X_train, y_train)

AdaBoostRegressor()

In [75]:
y_pred = AdaB.predict(X_test)
y_pred

array([0.65386364, 0.59636042, 0.73405063, 0.75758242, 0.75621622,
       0.65386364, 0.83421053, 0.69128   ])

In [76]:
mse = mean_squared_error(y_test, y_pred)
mse

0.005871352268919825

In [77]:
mae = mean_absolute_error(y_test, y_pred)
mae

0.061891563777330724

In [78]:
rmse = np.sqrt(mse)
rmse

0.07662474971521815

In [79]:
r2 = r2_score(y_test, y_pred)
r2

0.3694134163267849

In [80]:
#Uising Decision Tree

data = cleaned_data
target_col = 'Chance_of_Admit' 
test_size = 0.2
seed = 42
model=DecisionTreeRegressor()
X_train, X_test, y_train, y_test,y_pred= model_training(data, target_col, model, test_size, seed)
y_pred_dec = y_pred

In [81]:
model

DecisionTreeRegressor()

In [82]:
score

0.8501602905834911

Industrializing the best model
# Putting together all the important steps towards model building

In [83]:
#model Inferencing

In [84]:
scaler

StandardScaler()

In [85]:
log_reg

LinearRegression()

In [86]:
cleaned_data

GRE_Score  TOEFL_Score  University_Rating       SOP      LOR       CGPA  \
0     1.762107     1.746971           0.798829  1.093864  1.167321  1.764818   
1     0.627656    -0.067635           0.798829  0.596653  1.167321  0.455151   
2    -0.070467    -0.562528          -0.076600 -0.397769  0.052933 -1.005631   
3     0.453126     0.427257          -0.076600  0.099442 -1.061454  0.119339   
4    -0.244998    -0.727492          -0.952029 -1.392191 -0.504260 -0.653029   
..         ...          ...                ...       ...       ...       ...   
395   0.627656     0.427257          -0.076600  0.099442  0.052933  0.740592   
396   0.714922    -0.067635          -0.076600 -0.397769  0.052933  0.858126   
397   1.151249     1.417042           0.798829  1.591075  1.167321  1.429006   
398  -0.419528    -0.727492          -0.076600  0.099442  0.610127  0.304036   
399   1.413045     1.582006           0.798829  1.591075  0.610127  1.781609   

     Research  Chance_of_Admit  
0    0.909112             0.92  
1    0.909112             0.76  
2    0.909112             0.72  
3    0.909112             0.80  
4   -1.099975             0.65  
..        ...              ...  
395  0.909112             0.82  
396  0.909112             0.84  
397  0.909112             0.91  
398 -1.099975             0.67  
399  0.909112             0.95  

[400 rows x 8 columns]

In [87]:
scaler
log_reg



LinearRegression()

In [88]:
def preprocessing_and_prediction(GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research):
    

    input_cols = ['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR ', 'CGPA', 'Research']


    input_data = np.array([[GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research]])
    input_df = pd.DataFrame(input_data, columns=Num_cols)
    num_trans = scaler.transform(input_df)
    num_df = pd.DataFrame(num_trans, columns=Num_cols)
    predictions = model.predict(num_df)
    pred_df = pd.DataFrame(predictions, columns=['Admission_chances '])
    output = pd.concat([input_df, round(pred_df*100,2)], axis=1)
    return output



In [89]:
preprocessing_and_prediction(GRE_Score=320, TOEFL_Score=110, University_Rating=4, SOP=4.3, LOR=4.2, CGPA=8.3, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0      320.0        110.0                4.0  4.3   4.2   8.3       1.0   

   Admission_chances   
0                64.0

In [90]:
preprocessing_and_prediction(GRE_Score=320, TOEFL_Score=110, University_Rating=4, SOP=4.3, LOR=4.2, CGPA=8.3, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0      320.0        110.0                4.0  4.3   4.2   8.3       1.0   

   Admission_chances   
0                64.0

In [91]:
preprocessing_and_prediction(GRE_Score=300, TOEFL_Score=100, University_Rating=3, SOP=4, LOR=4, CGPA=8, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0        300          100                  3    4     4     8         1   

   Admission_chances   
0                48.0

In [92]:
#Using Adaboost model
AdaB

AdaBoostRegressor()

In [93]:


def preprocessing_and_prediction(GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research):
    

    input_cols = ['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR ', 'CGPA', 'Research']


    input_data = np.array([[GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research]])
    input_df = pd.DataFrame(input_data, columns=Num_cols)
    num_trans = scaler.transform(input_df)
    num_df = pd.DataFrame(num_trans, columns=Num_cols)
    predictions = AdaB.predict(num_df)
    pred_df = pd.DataFrame(predictions, columns=['Admission_chances '])
    output = pd.concat([input_df, round(pred_df*100,2)], axis=1)
    return output

In [94]:
preprocessing_and_prediction(GRE_Score=320, TOEFL_Score=110, University_Rating=4, SOP=4.3, LOR=4.2, CGPA=8.3, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0      320.0        110.0                4.0  4.3   4.2   8.3       1.0   

   Admission_chances   
0               69.44

In [95]:
preprocessing_and_prediction(GRE_Score=300, TOEFL_Score=100, University_Rating=3, SOP=4, LOR=4, CGPA=8, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0        300          100                  3    4     4     8         1   

   Admission_chances   
0               57.57

In [96]:
#using Decision Tree Model 
DecisionModel

DecisionTreeRegressor()

In [97]:
def preprocessing_and_prediction(GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research):
    

    input_cols = ['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR ', 'CGPA', 'Research']


    input_data = np.array([[GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research]])
    input_df = pd.DataFrame(input_data, columns=Num_cols)
    num_trans = scaler.transform(input_df)
    num_df = pd.DataFrame(num_trans, columns=Num_cols)
    predictions = DecisionModel.predict(num_df)
    pred_df = pd.DataFrame(predictions, columns=['Admission_chances '])
    output = pd.concat([input_df, round(pred_df*100,2)], axis=1)
    return output

In [98]:
preprocessing_and_prediction(GRE_Score=320, TOEFL_Score=110, University_Rating=4, SOP=4.3, LOR=4.2, CGPA=8.3, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0      320.0        110.0                4.0  4.3   4.2   8.3       1.0   

   Admission_chances   
0                79.0

In [99]:
preprocessing_and_prediction(GRE_Score=300, TOEFL_Score=100, University_Rating=3, SOP=4, LOR=4, CGPA=8, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0        300          100                  3    4     4     8         1   

   Admission_chances   
0                68.0

In [100]:
preprocessing_and_prediction(GRE_Score=290, TOEFL_Score=98, University_Rating=4, SOP=4, LOR=4, CGPA=8, Research=1)

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR   CGPA  Research  \
0        290           98                  4    4     4     8         1   

   Admission_chances   
0                68.0

In [101]:
!pip install gradio


In [102]:
import gradio as gr

In [103]:
scaler
model

def preprocessing_and_prediction_for_gradio(GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research):

    input_cols = ['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR ', 'CGPA', 'Research']
    
    input_data = np.array([[GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research]])

    input_df = pd.DataFrame(input_data, columns=input_cols)

    num_trans = scaler.transform(input_df)
    num_df = pd.DataFrame(num_trans, columns=input_cols)

    predictions = model.predict(num_df)
    pred_df = pd.DataFrame(predictions, columns=['Admission_chances'])
    
    return pred_df

In [104]:
inputs = [
    gr.Number(label='GRE_Score'),
    gr.Number(label='TOEFL_Score'),
    gr.Number(label='University_Rating'),
    gr.Number(label='SOP'),
    gr.Number(label='LOR'),
    gr.Number(label='CGPA'),
    gr.Number(label='Research')       
]

outputs = [gr.Dataframe(row_count = (1, 'dynamic'), col_count = (1, 'fixed'), label='Admission_chances', headers=['prediction'])]

title = 'Ezeaku_Model'
description = 'This machine learning admission app allows you to determine your chances of been admitted to graduate school'

interface = gr.Interface(
    fn = preprocessing_and_prediction_for_gradio, inputs=inputs, outputs=outputs, title=title, description=description
)

In [105]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860


Exception in thread Thread-9 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpx\_transports\default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\DOC\anaconda3\lib\site-packages\httpcore\_sync\connecti

Running on public URL: https://f4dfb95d2a79460ea2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
